#!/usr/bin/env python3
import sys, hashlib, signal

# --------------------------------
# Colors
# --------------------------------
red = "\033[31m"
green = "\033[32m"
end = "\033[0m"

def get_algos(length):
    algos = {
        32: "md5",
        40: "sha-1",
        56: "sha-224",
        64: "sha-256",
        96: "sha-384",
        128: "sha-512"    
    }

    return algos.get(length, "")

def verify(input_hash, file_hash, file, algo):

    if len(input_hash) == len(file_hash):
        if input_hash == file_hash:
            print(f"\nThe hashes match correctly")
            print(f"{green}The file is already secure{end}\n")

            if algo == 'md5' or algo == 'sha-1':
                print(f"{red}The {algo} algorithm is not secure today, if you really want to verify the file try to use another hash algorithm{end}") 
    
        else:
            print(f"The file hash: {file_hash} and hash given: {input_hash} does not match")
            print(f"{red}This file is not secure with the given hash{end}")

def get_hash(file, algo):
    h = hashlib.new(algo)

    with open(file, "rb") as f:
        for x in iter(lambda: f.read(4096), b""):
            h.update(x)

    return h.hexdigest()


def main():

    file = sys.argv[1]
    input_hash = sys.argv[2]
    input_hash = str(input_hash)

    length = len(input_hash)
    algo = get_algos(length)

    if not algo:
        print("Not algorithm supported")
        print("Algorithms supported: md5, sha-1, sha-224, sha-256, sha-384, sha-512")
        sys.exit(1)

    file_hash = get_hash(file, algo)

    #print(f"\nPath: {file}")
    #print(f"Hash: {input_hash}")
    #print(f"Algorithm: {algo}")
    #print(f"File Hash: {file_hash}\n")

    verify(input_hash, file_hash, file, algo)

if __name__=='__main__':
    main()
